---
vetter:
  western: Tim Gutowski <tgutowski-western@trilogyinteractive.com>
  southern: Tim Gutowski <tgutowski-souther@trilogyinteractive.com>
  eastern: Tim Gutowski <tgutowski-eastern@trilogyinteractive.com>
  central: Tim Gutowski <tgutowski-central@trilogyinteractive.com>
  default: Tim Gutowski <tgutowski-default@trilogyinteractive.com>
nagger: Tim Gutowski <tgutowski-nagger@trilogyinteractive.com>