---
vetter:
  western: Jashua Bane <JBane@afscme.org>
  southern: John Noonan <JNoonan@afscme.org>
  eastern: John Noonan <JNoonan@afscme.org>
  central: John Noonan <JNoonan@afscme.org>
  default: John Noonan <JNoonan@afscme.org>
  n/a: John Noonan <JNoonan@afscme.org>
nagger: John Noonan <JNoonan@afscme.org>