class AddPaperclipMigrationData < ActiveRecord::Migration[5.2]
  def change
    add_column :images,       :original_image_url, :text # The path to the original image generated by Paperclip
    add_column :images,       :cropped_image_url,  :text # The path of the cropped image generated by Paperclip. The imgix URLs will also go here.
    add_column :templates,    :thumbnail_url,      :text
    add_column :templates,    :numbered_image_url, :text
    add_column :templates,    :blank_image_url,    :text
    add_column :templates,    :static_pdf_url,     :text
    add_column :stock_images, :image_url,          :text
    add_column :documents,    :pdf_url,            :text
    add_column :documents,    :thumbnail_url,      :text
    add_column :documents,    :share_graphic_url,  :text
    add_column :documents,    :generated,          :boolean, default: false
  end
end
